# =========================
# Build stage
# =========================
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Copy solution and projects
COPY TaskeemBackend.slnx ./
COPY Taskeem.Api/Taskeem.Api.csproj ./Taskeem.Api/
COPY Taskeem.Domain/Taskeem.Domain.csproj ./Taskeem.Domain/
COPY Taskeem.Domain.EF/Taskeem.Domain.EF.csproj ./Taskeem.Domain.EF/
COPY Taskeem.Domain.EF.Tests/Taskeem.Domain.EF.Tests.csproj ./Taskeem.Domain.EF.Tests/

# Restore packages
RUN dotnet restore

# Copy all source code
COPY . .

RUN dotnet publish Taskeem.Api/Taskeem.Api.csproj -c Release -o /app/publish

# =========================
# Runtime stage
# =========================
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

EXPOSE 8080

COPY --from=build /app/publish .
COPY --from=build /src/Taskeem.Api/entrypoint.sh .

ENTRYPOINT ["./entrypoint.sh"]
